#!/bin/bash

function getuptime () {
  snmpget -v 2c -c snmpcol1 -O n $1 .1.3.6.1.2.1.1.3.0 | gawk '{ print $4 }' | gawk -F\( '{ print $2 }' | gawk -F\) '{ print $1 }'
}

for i in `echo "select id from nethosts" | $DBQ`; do
  sysName=`echo "select hostname from nethosts where id='$i'" | $DBQ`
  sysUptime=`getuptime $sysName`
  CurrTimeSecs=`date +%s`
  echo "update nethosts set uptime='$sysUptime',lastchecked='$CurrTimeSecs' where id='$i'" | $DBQ
done

snmp/sensatronics-em1.snmp
